
---
##  [ 힌트 ]  기존의 모델했던 예제에서 모델링만 변경하면 된다


from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)

- 매개변수
- n_estimators : 랜덤포레스트 모델을 만들 때 생성할 트리의 갯수
- random_state : 램덤 시드값으로 같은 결과를 만들려면 random_state 값을 고정한다.
- 그러나 랜덤포레스트의 트리가 많을수록 random_state 값의 변화에 따른 변동이 적다


---

In [28]:
import pandas as pd
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

# (1) 데이타 읽어오기 (pandas 이용)
csv = pd.read_csv('../data/iris/iris.csv')
#print(csv[:10]) # 컬럼명이 0번째 레코드(샘플)과 분리되어 있음

# (2) 데이터와 레이블 분리 변수 선언 (실제 iris.csv 파일 컬럼명 확인)
csv_data = csv[['sepal.length','sepal.width','petal.length','petal.width']]
csv_label = csv['variety']
# print(csv_data.head())
# print(csv_label.head())

# (3) 훈련데이터와 테스트 데이터로 분리하기

X_train, X_test, y_train, y_test = train_test_split(csv_data, csv_label, test_size=0.7) 

# (4) 분류모델로 학습하기
#     예를 들면, clf = svm.SVC(gamma='auto')  이렇게 학습 모델 지정하기

#model = RandomForestClassifier()
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

# (5) 예측하기
y_predict = model.predict(X_test)

# (6) 검증하기
ac_score = metrics.accuracy_score(y_test, y_predict)
ac_score
#model.score(X_test, y_test)

0.9523809523809523

In [24]:
X_test

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
137           6.4          3.1           5.5          1.8
13            4.3          3.0           1.1          0.1
62            6.0          2.2           4.0          1.0
89            5.5          2.5           4.0          1.3
..            ...          ...           ...          ...
109           7.2          3.6           6.1          2.5
135           7.7          3.0           6.1          2.3
38            4.4          3.0           1.3          0.2
23            5.1          3.3           1.7          0.5
11            4.8          3.4           1.6          0.2

[105 rows x 4 columns]